name: Python CI File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: Install dependecies
        run: |
          pip install -r requirement.txt
      
      - name: Run Python Script
        run:  python app.py